sudo: required

notifications:
  email: false

language: python
python:
 - "2.7"

install:
 - pip install -r requirements.txt

script:
 - coverage run --source=. --omit=./tests/* -m nose
 - coverage report
